### ISSUE TITLE
Why should I set the run button as?

### ISSUE THREAD

**Issue by RoundingExplorer** [HarryPotter12352/settup#8]
![image](https://user-images.githubusercontent.com/71095068/125150853-89cdad80-e160-11eb-8a43-a10d02b3b43c.png)

**Comment by RoundingExplorer** [comment]
@HarryPotter12352

**Comment by HarryPotter12352** [comment]
Please check if you actually configured a proper main.py file, and it does look like you clicked on the clone button, which resulted in a non pythonic repl, therefore you had to configure an interpreter
